spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplepay
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/simplepay?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
jwt:
  secret: mock-secret-for-dev-and-test-1234567890